### ISSUE TITLE
Console Errors

### ISSUE THREAD

**Issue by sty1ee** [amoerie/teamcity-theatre#17]
Hi,

I'm getting this error when running the dashboard in chrome console.

{message: "An error has occurred.",…}
exceptionMessage
:
"An error occurred when trying to create a controller of type 'ProjectsController'. Make sure that the controller has a parameterless public constructor."
exceptionType
:
"System.InvalidOperationException"
innerException
:
{message: "An error has occurred.",…}
message
:
"An error has occurred."
stackTrace
:
"   at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType)
↵   at System.Web.Http.Controllers.HttpControllerDescriptor.CreateController(HttpRequestMessage request)
↵   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
Name

I'm running the app locally. It will actually load but # the build configuration will not pick up teamcity

![image](https://cloud.githubusercontent.com/assets/16201158/26387802/acc9442e-4093-11e7-829e-e80e3ebe584a.png)

I have modified the web.config with url and credentials and confirmed they work. I also tried different networks to confirm its not my locked down work network. Any ideas about how to go about rectifying this.

Windows 10
.Net 4.5 installed
Running in Chrome v58
IIS Version 10

![image](https://cloud.githubusercontent.com/assets/16201158/26387809/c238fcb4-4093-11e7-9d96-d9edf6f6d0f6.png)

I'm new to IIS and also developing. So apologies if something is obvious.

Cheers,

Lee

**Comment by sty1ee** [comment]
Worked on configuration issue.
